platform :ios,'9.0'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
inhibit_all_warnings!

abstract_target 'CocoaPods' do
    pod 'EasyPeasy'
    pod 'SwiGradientTransition', :path => '../'
  target 'SwiGradientTransitionDemo' do
      
  end
  
  # Disable Code Coverage for Pods projects
  post_install do |installer_representation|
      installer_representation.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['CLANG_ENABLE_CODE_COVERAGE'] = 'NO'
          end
      end
  end
end

